import {
  UserProfile,
  Customer,
  Booking,
  PaymentRecord,
  FollowUp,
  Task,
  Employee,
  AttendanceRecord,
  LeaveRequest,
  Holiday,
  CustomField,
  AutomationRule,
  AuditLog,
  DocumentItem,
  SalesTeam,
  WFHRequest,
  Notification as CRMNotification,
  PinnedDevice
} from '@/types/crm';

/**
 * Root Super Admin profile — maintained for initial authentication
 */
export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'u-1',
    name: 'Satya Sharma',
    email: 'cso@satyasupport.co.in',
    password: 'akash@802',
    department: 'Executive',
    designation: 'Chief Strategy Officer & Founder',
    role: 'SUPER_ADMIN',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 09:45 PM',
    createdDate: '15 Jan 2025',
    branch: 'Corporate HQ',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit', 'sales.leads.delete',
      'sales.bookings.view', 'sales.bookings.create', 'sales.bookings.edit',
      'sales.payments.view', 'sales.payments.manage',
      'hr.employees.view', 'hr.employees.create', 'hr.employees.edit',
      'attendance.view', 'attendance.manage',
      'users.view', 'users.create', 'users.edit', 'users.manage_roles',
      'system.settings', 'system.custom_fields', 'system.automation', 'system.integrations', 'system.audit_logs'
    ]
  },
  {
    id: 'u-rm',
    name: 'Rajesh Nair',
    email: 'rm@satyasupport.co.in',
    password: 'akash@802',
    department: 'Sales',
    designation: 'Regional Manager (West & North Zone)',
    role: 'RM',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 08:30 PM',
    createdDate: '15 Jan 2025',
    branch: 'West Zone HQ',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit',
      'sales.bookings.view', 'sales.bookings.create', 'sales.bookings.edit',
      'sales.payments.view', 'hr.employees.view', 'attendance.view', 'attendance.manage', 'users.view'
    ]
  },
  {
    id: 'u-bm',
    name: 'Pooja Deshmukh',
    email: 'bm@satyasupport.co.in',
    password: 'akash@802',
    department: 'Sales',
    designation: 'Branch Operations Manager',
    role: 'BRANCH_MANAGER',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 06:15 PM',
    createdDate: '15 Jan 2025',
    branch: 'Mumbai Central Branch',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit',
      'sales.bookings.view', 'sales.bookings.create', 'sales.bookings.edit',
      'sales.payments.view', 'hr.employees.view', 'attendance.view', 'users.view'
    ]
  },
  {
    id: 'u-tl',
    name: 'Vikram Rathore',
    email: 'tl@satyasupport.co.in',
    password: 'akash@802',
    department: 'Sales',
    designation: 'Govt Schemes & Subsidy Team Lead',
    role: 'TL',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 07:10 PM',
    createdDate: '15 Jan 2025',
    branch: 'Mumbai Central Branch',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit',
      'sales.bookings.view', 'sales.bookings.create', 'sales.bookings.edit',
      'sales.payments.view', 'attendance.view'
    ]
  },
  {
    id: 'u-bdm',
    name: 'Neha Mehta',
    email: 'bdm@satyasupport.co.in',
    password: 'akash@802',
    department: 'Sales',
    designation: 'Business Development Manager (Loans)',
    role: 'BDM',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 05:40 PM',
    createdDate: '15 Jan 2025',
    branch: 'Mumbai Central Branch',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit',
      'sales.bookings.view', 'sales.bookings.create', 'sales.payments.view', 'attendance.view'
    ]
  },
  {
    id: 'u-bde',
    name: 'Rohan Patil',
    email: 'bde@satyasupport.co.in',
    password: 'akash@802',
    department: 'Sales',
    designation: 'Business Development Executive (IT & Grants)',
    role: 'BDE',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 04:20 PM',
    createdDate: '15 Jan 2025',
    branch: 'Mumbai Central Branch',
    permissions: [
      'sales.leads.view', 'sales.leads.create', 'sales.leads.edit',
      'sales.bookings.view', 'attendance.view'
    ]
  },
  {
    id: 'u-hr',
    name: 'Priya Iyer',
    email: 'hr@satyasupport.co.in',
    password: 'akash@802',
    department: 'HR',
    designation: 'Head of Human Resources',
    role: 'HR',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 05:00 PM',
    createdDate: '15 Jan 2025',
    branch: 'Corporate HQ',
    permissions: [
      'hr.employees.view', 'hr.employees.create', 'hr.employees.edit',
      'attendance.view', 'attendance.manage', 'users.view', 'users.create', 'users.edit'
    ]
  },
  {
    id: 'u-tech',
    name: 'Aman Verma (IT & Tech Lead)',
    email: 'tech@satyasupport.co.in',
    password: 'akash@802',
    department: 'Tech',
    designation: 'Lead Systems & Security Engineer',
    role: 'TECH',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '23 Sep 2026, 10:15 PM',
    createdDate: '15 Jan 2025',
    branch: 'Corporate HQ',
    permissions: [
      'system.settings', 'system.device_pinning', 'system.custom_fields', 'system.automation', 'system.integrations', 'system.audit_logs',
      'users.view', 'attendance.view'
    ]
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'e-1',
    name: 'Satya Sharma',
    email: 'cso@satyasupport.co.in',
    phone: '+91 98111 22334',
    department: 'Executive',
    designation: 'Chief Strategy Officer & Founder',
    role: 'SUPER_ADMIN',
    reportingManager: 'Board of Directors',
    joiningDate: '01 Jan 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-001',
    branch: 'Corporate HQ',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Executive Team'
  },
  {
    id: 'e-rm',
    name: 'Rajesh Nair',
    email: 'rm@satyasupport.co.in',
    phone: '+91 98111 55667',
    department: 'Sales',
    designation: 'Regional Manager (West & North Zone)',
    role: 'RM',
    reportingManager: 'Satya Sharma',
    joiningDate: '15 Jan 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-RM-01',
    branch: 'West Zone HQ',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Regional Leadership'
  },
  {
    id: 'e-bm',
    name: 'Pooja Deshmukh',
    email: 'bm@satyasupport.co.in',
    phone: '+91 98222 66778',
    department: 'Sales',
    designation: 'Branch Operations Manager',
    role: 'BRANCH_MANAGER',
    reportingManager: 'Rajesh Nair',
    joiningDate: '01 Feb 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-BM-01',
    branch: 'Mumbai Central Branch',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Branch Management'
  },
  {
    id: 'e-tl',
    name: 'Vikram Rathore',
    email: 'tl@satyasupport.co.in',
    phone: '+91 98333 77889',
    department: 'Sales',
    designation: 'Govt Schemes & Subsidy Team Lead',
    role: 'TL',
    reportingManager: 'Pooja Deshmukh',
    joiningDate: '15 Feb 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-TL-01',
    branch: 'Mumbai Central Branch',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Schemes & Grants Pod'
  },
  {
    id: 'e-bdm',
    name: 'Neha Mehta',
    email: 'bdm@satyasupport.co.in',
    phone: '+91 98444 88990',
    department: 'Sales',
    designation: 'Business Development Manager (Loans)',
    role: 'BDM',
    reportingManager: 'Vikram Rathore',
    joiningDate: '01 Mar 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-BDM-01',
    branch: 'Mumbai Central Branch',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Debt & Loans Pod'
  },
  {
    id: 'e-bde',
    name: 'Rohan Patil',
    email: 'bde@satyasupport.co.in',
    phone: '+91 98555 99001',
    department: 'Sales',
    designation: 'Business Development Executive (IT & Grants)',
    role: 'BDE',
    reportingManager: 'Neha Mehta',
    joiningDate: '15 Mar 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-BDE-01',
    branch: 'Mumbai Central Branch',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Sales Execution Pod'
  },
  {
    id: 'e-hr',
    name: 'Priya Iyer',
    email: 'hr@satyasupport.co.in',
    phone: '+91 98666 11223',
    department: 'HR',
    designation: 'Head of Human Resources',
    role: 'HR',
    reportingManager: 'Satya Sharma',
    joiningDate: '01 Feb 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-HR-01',
    branch: 'Corporate HQ',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'Human Resources'
  },
  {
    id: 'e-tech',
    name: 'Aman Verma (IT & Tech Lead)',
    email: 'tech@satyasupport.co.in',
    phone: '+91 98222 33445',
    department: 'Tech',
    designation: 'Lead Systems & Security Engineer',
    role: 'TECH',
    reportingManager: 'Satya Sharma',
    joiningDate: '01 Feb 2024',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    employeeCode: 'EMP-TECH-01',
    branch: 'Corporate HQ',
    leadsHandled: 0,
    bookingsCount: 0,
    revenueGenerated: 0,
    conversionRate: '0%',
    teamName: 'IT & Infrastructure'
  }
];

// ZERO FAKE DATA — All collections initialized as clean empty arrays
export const INITIAL_CUSTOMERS: Customer[] = [];
export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'BK-2026-0101',
    customerId: 'cust-01',
    customerName: 'Aarav Singhania',
    companyName: 'Singhania Agro Industries Pvt Ltd',
    services: ['CGTMSE Collateral-Free MSME Credit'],
    assignedSalesperson: 'Neha Mehta',
    assignedSalespersonId: 'm-01-1',
    createdById: 'm-01-1',
    createdByName: 'Neha Mehta',
    clientEmail: 'singhania@agro.in',
    clientMobile: '9820199182',
    branchName: 'Mumbai Central Branch',
    bookingDate: '2026-09-18',
    expectedAmount: 220000,
    paidAmount: 220000,
    pendingAmount: 0,
    paymentStatus: 'Paid',
    serviceStatus: 'Completed',
    expectedCompletionDate: '2026-09-25',
    documentsStatus: 'Verified',
    category: 'BUSINESS_LOANS'
  },
  {
    id: 'BK-2026-0102',
    customerId: 'cust-02',
    customerName: 'Kavita Chidambaram',
    companyName: 'Chidambaram Green Tech Solutions',
    services: ['PMEGP Subsidy Assistance Program (35% Grant)'],
    assignedSalesperson: 'Rohan Patil',
    assignedSalespersonId: 'm-01-2',
    createdById: 'm-01-2',
    createdByName: 'Rohan Patil',
    clientEmail: 'kavita@chidambaramtech.in',
    clientMobile: '9845012398',
    branchName: 'Mumbai Central Branch',
    bookingDate: '2026-09-21',
    expectedAmount: 185000,
    paidAmount: 185000,
    pendingAmount: 0,
    paymentStatus: 'Paid',
    serviceStatus: 'In Progress',
    expectedCompletionDate: '2026-10-05',
    documentsStatus: 'Verified',
    category: 'GOVERNMENT_GRANTS'
  },
  {
    id: 'BK-2026-0103',
    customerId: 'cust-03',
    customerName: 'Rameshwar Kulkarni',
    companyName: 'Kulkarni Precision Tooling LLP',
    services: ['CLCSS Technology Upgradation Grant'],
    assignedSalesperson: 'Aakash Yadav',
    assignedSalespersonId: 'm-01-3',
    createdById: 'm-01-3',
    createdByName: 'Aakash Yadav',
    clientEmail: 'rameshwar@kulkarnitools.com',
    clientMobile: '9890123456',
    branchName: 'Mumbai Central Branch',
    bookingDate: '2026-09-24',
    expectedAmount: 160000,
    paidAmount: 80000,
    pendingAmount: 80000,
    paymentStatus: 'Partially Paid',
    serviceStatus: 'Under Processing',
    expectedCompletionDate: '2026-10-10',
    documentsStatus: 'Verified',
    category: 'GOVERNMENT_SCHEMES'
  }
];
export const INITIAL_PAYMENTS: PaymentRecord[] = [];
export const INITIAL_DOCUMENTS: DocumentItem[] = [];
export const INITIAL_FOLLOWUPS: FollowUp[] = [];
export const INITIAL_TASKS: Task[] = [];
export const INITIAL_ATTENDANCE: AttendanceRecord[] = [];
export const INITIAL_LEAVES: LeaveRequest[] = [];
export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 'hol-001', name: 'Republic Day', date: '2026-01-26', day: 'Monday', type: 'National', description: 'National Republic Day Celebration' },
  { id: 'hol-002', name: 'Maha Shivratri', date: '2026-02-15', day: 'Sunday', type: 'Gazetted', description: 'Gazetted Holiday' },
  { id: 'hol-003', name: 'Holi (Festival of Colors)', date: '2026-03-04', day: 'Wednesday', type: 'Gazetted', description: 'Spring Festival Holiday' },
  { id: 'hol-004', name: 'Id-ul-Fitr (Ramzan Id)', date: '2026-03-21', day: 'Saturday', type: 'Gazetted', description: 'Islamic Gazetted Holiday' },
  { id: 'hol-005', name: 'Mahavir Jayanti', date: '2026-03-31', day: 'Tuesday', type: 'Gazetted', description: 'Gazetted Holiday' },
  { id: 'hol-006', name: 'Good Friday', date: '2026-04-03', day: 'Friday', type: 'Gazetted', description: 'Christian Gazetted Holiday' },
  { id: 'hol-007', name: 'Buddha Purnima', date: '2026-05-31', day: 'Sunday', type: 'Gazetted', description: 'Gazetted Holiday' },
  { id: 'hol-008', name: 'Bakrid / Eid-ul-Adha', date: '2026-05-27', day: 'Wednesday', type: 'Gazetted', description: 'Gazetted Holiday' },
  { id: 'hol-009', name: 'Independence Day', date: '2026-08-15', day: 'Saturday', type: 'National', description: 'National Independence Day Celebration' },
  { id: 'hol-010', name: 'Milad-un-Nabi (Id-e-Milad)', date: '2026-08-26', day: 'Wednesday', type: 'Gazetted', description: 'Prophet Birthday' },
  { id: 'hol-011', name: 'Mahatma Gandhi Jayanti', date: '2026-10-02', day: 'Friday', type: 'National', description: 'National Holiday' },
  { id: 'hol-012', name: 'Dussehra (Vijay Dashami)', date: '2026-10-20', day: 'Tuesday', type: 'Gazetted', description: 'Autumn Festival' },
  { id: 'hol-013', name: 'Diwali (Deepavali)', date: '2026-11-08', day: 'Sunday', type: 'Gazetted', description: 'Festival of Lights' },
  { id: 'hol-014', name: 'Govardhan Puja', date: '2026-11-09', day: 'Monday', type: 'Restricted', description: 'Restricted / Optional Holiday' },
  { id: 'hol-015', name: 'Bhai Duj', date: '2026-11-10', day: 'Tuesday', type: 'Restricted', description: 'Restricted / Optional Holiday' },
  { id: 'hol-016', name: 'Guru Nanak Jayanti', date: '2026-11-24', day: 'Tuesday', type: 'Gazetted', description: 'Sikh Festival' },
  { id: 'hol-017', name: 'Christmas Day', date: '2026-12-25', day: 'Friday', type: 'Gazetted', description: 'Winter Holiday' }
];
export const INITIAL_CUSTOM_FIELDS: CustomField[] = [];
export const INITIAL_AUTOMATIONS: AutomationRule[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_NOTIFICATIONS: CRMNotification[] = [];
export const INITIAL_TEAMS: SalesTeam[] = [
  {
    id: 'team-01',
    name: 'Team 01 - Alpha Titans',
    division: 'Government Grants & Funding',
    branchName: 'Mumbai Central Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'e-tl',
    teamLeadName: 'Vikram Rathore',
    targetRevenue: 1500000,
    achievedRevenue: 1385000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['e-bdm', 'm-01-5'],
    bdmNames: ['Neha Mehta', 'Nikhil Rane'],
    bdeIds: ['e-bde', 'm-01-3', 'm-01-4'],
    bdeNames: ['Rohan Patil', 'Aakash Yadav', 'Shreya Joshi'],
    members: [
      { id: 'm-01-1', name: 'Neha Mehta', role: 'BDM', targetRevenue: 350000, achievedRevenue: 345000 },
      { id: 'm-01-2', name: 'Rohan Patil', role: 'BDE', targetRevenue: 300000, achievedRevenue: 290000 },
      { id: 'm-01-3', name: 'Aakash Yadav', role: 'BDE', targetRevenue: 300000, achievedRevenue: 275000 },
      { id: 'm-01-4', name: 'Shreya Joshi', role: 'BDE', targetRevenue: 280000, achievedRevenue: 255000 },
      { id: 'm-01-5', name: 'Nikhil Rane', role: 'BDM', targetRevenue: 270000, achievedRevenue: 220000 }
    ]
  },
  {
    id: 'team-02',
    name: 'Team 02 - Beta Predators',
    division: 'Business Loans & MSME Credit',
    branchName: 'Mumbai Central Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-02',
    teamLeadName: 'Ananya Sen',
    targetRevenue: 1500000,
    achievedRevenue: 1180000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-02-1', 'm-02-5'],
    bdmNames: ['Gaurav Kulkarni', 'Priya Chawla'],
    bdeIds: ['m-02-2', 'm-02-3', 'm-02-4'],
    bdeNames: ['Sneha Kapoor', 'Manish Dave', 'Karan Malhotra'],
    members: [
      { id: 'm-02-1', name: 'Gaurav Kulkarni', role: 'BDM', targetRevenue: 350000, achievedRevenue: 290000 },
      { id: 'm-02-2', name: 'Sneha Kapoor', role: 'BDE', targetRevenue: 300000, achievedRevenue: 250000 },
      { id: 'm-02-3', name: 'Manish Dave', role: 'BDE', targetRevenue: 300000, achievedRevenue: 240000 },
      { id: 'm-02-4', name: 'Karan Malhotra', role: 'BDE', targetRevenue: 280000, achievedRevenue: 210000 },
      { id: 'm-02-5', name: 'Priya Chawla', role: 'BDM', targetRevenue: 270000, achievedRevenue: 190000 }
    ]
  },
  {
    id: 'team-03',
    name: 'Team 03 - Gamma Strikers',
    division: 'Government Schemes & Subsidies',
    branchName: 'Pune West Hub',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-03',
    teamLeadName: 'Amit Trivedi',
    targetRevenue: 1500000,
    achievedRevenue: 1310000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-03-1', 'm-03-2'],
    bdmNames: ['Siddharth Rao', 'Pooja Agarwal'],
    bdeIds: ['m-03-3', 'm-03-4', 'm-03-5'],
    bdeNames: ['Vikas Pandey', 'Neha Kadam', 'Kunal Verma'],
    members: [
      { id: 'm-03-1', name: 'Siddharth Rao', role: 'BDM', targetRevenue: 350000, achievedRevenue: 320000 },
      { id: 'm-03-2', name: 'Pooja Agarwal', role: 'BDM', targetRevenue: 320000, achievedRevenue: 290000 },
      { id: 'm-03-3', name: 'Vikas Pandey', role: 'BDE', targetRevenue: 280000, achievedRevenue: 250000 },
      { id: 'm-03-4', name: 'Neha Kadam', role: 'BDE', targetRevenue: 280000, achievedRevenue: 240000 },
      { id: 'm-03-5', name: 'Kunal Verma', role: 'BDE', targetRevenue: 270000, achievedRevenue: 210000 }
    ]
  },
  {
    id: 'team-04',
    name: 'Team 04 - Delta Warriors',
    division: 'IT Services & SaaS',
    branchName: 'Pune West Hub',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-04',
    teamLeadName: 'Sunita Rao',
    targetRevenue: 1500000,
    achievedRevenue: 1060000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-04-1'],
    bdmNames: ['Aditya Joshi'],
    bdeIds: ['m-04-2', 'm-04-3', 'm-04-4', 'm-04-5'],
    bdeNames: ['Kavya Pillai', 'Deepak Ghosh', 'Harsh Solanki', 'Ritika Sen'],
    members: [
      { id: 'm-04-1', name: 'Aditya Joshi', role: 'BDM', targetRevenue: 360000, achievedRevenue: 270000 },
      { id: 'm-04-2', name: 'Kavya Pillai', role: 'BDE', targetRevenue: 290000, achievedRevenue: 220000 },
      { id: 'm-04-3', name: 'Deepak Ghosh', role: 'BDE', targetRevenue: 290000, achievedRevenue: 210000 },
      { id: 'm-04-4', name: 'Harsh Solanki', role: 'BDE', targetRevenue: 280000, achievedRevenue: 190000 },
      { id: 'm-04-5', name: 'Ritika Sen', role: 'BDE', targetRevenue: 280000, achievedRevenue: 170000 }
    ]
  },
  {
    id: 'team-05',
    name: 'Team 05 - Phoenix Mavericks',
    division: 'Government Grants & Funding',
    branchName: 'Delhi NCR Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-05',
    teamLeadName: 'Rohit Kashyap',
    targetRevenue: 1500000,
    achievedRevenue: 1245000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-05-1', 'm-05-2'],
    bdmNames: ['Ashish Mathur', 'Kriti Bajaj'],
    bdeIds: ['m-05-3', 'm-05-4', 'm-05-5'],
    bdeNames: ['Mohit Chawla', 'Tanya Mehra', 'Varun Dhawan'],
    members: [
      { id: 'm-05-1', name: 'Ashish Mathur', role: 'BDM', targetRevenue: 350000, achievedRevenue: 300000 },
      { id: 'm-05-2', name: 'Kriti Bajaj', role: 'BDM', targetRevenue: 300000, achievedRevenue: 270000 },
      { id: 'm-05-3', name: 'Mohit Chawla', role: 'BDE', targetRevenue: 300000, achievedRevenue: 250000 },
      { id: 'm-05-4', name: 'Tanya Mehra', role: 'BDE', targetRevenue: 280000, achievedRevenue: 225000 },
      { id: 'm-05-5', name: 'Varun Dhawan', role: 'BDE', targetRevenue: 270000, achievedRevenue: 200000 }
    ]
  },
  {
    id: 'team-06',
    name: 'Team 06 - Apex Falcons',
    division: 'Business Loans & MSME Credit',
    branchName: 'Delhi NCR Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-06',
    teamLeadName: 'Preeti Nair',
    targetRevenue: 1500000,
    achievedRevenue: 930000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-06-1'],
    bdmNames: ['Devendra Soni'],
    bdeIds: ['m-06-2', 'm-06-3', 'm-06-4', 'm-06-5'],
    bdeNames: ['Sakshi Malik', 'Abhishek Dixit', 'Prateek Goel', 'Ritu Saxena'],
    members: [
      { id: 'm-06-1', name: 'Devendra Soni', role: 'BDM', targetRevenue: 360000, achievedRevenue: 240000 },
      { id: 'm-06-2', name: 'Sakshi Malik', role: 'BDE', targetRevenue: 290000, achievedRevenue: 200000 },
      { id: 'm-06-3', name: 'Abhishek Dixit', role: 'BDE', targetRevenue: 290000, achievedRevenue: 180000 },
      { id: 'm-06-4', name: 'Prateek Goel', role: 'BDE', targetRevenue: 280000, achievedRevenue: 160000 },
      { id: 'm-06-5', name: 'Ritu Saxena', role: 'BDE', targetRevenue: 280000, achievedRevenue: 150000 }
    ]
  },
  {
    id: 'team-07',
    name: 'Team 07 - Zenith Champions',
    division: 'Government Schemes & Subsidies',
    branchName: 'Bangalore Tech Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-07',
    teamLeadName: 'Kunal Kapoor',
    targetRevenue: 1500000,
    achievedRevenue: 1125000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-07-1', 'm-07-2'],
    bdmNames: ['Manoj Tiwari', 'Archana Iyer'],
    bdeIds: ['m-07-3', 'm-07-4', 'm-07-5'],
    bdeNames: ['Farhan Ali', 'Deepali More', 'Samir Khan'],
    members: [
      { id: 'm-07-1', name: 'Manoj Tiwari', role: 'BDM', targetRevenue: 350000, achievedRevenue: 280000 },
      { id: 'm-07-2', name: 'Archana Iyer', role: 'BDM', targetRevenue: 310000, achievedRevenue: 245000 },
      { id: 'm-07-3', name: 'Farhan Ali', role: 'BDE', targetRevenue: 290000, achievedRevenue: 220000 },
      { id: 'm-07-4', name: 'Deepali More', role: 'BDE', targetRevenue: 280000, achievedRevenue: 200000 },
      { id: 'm-07-5', name: 'Samir Khan', role: 'BDE', targetRevenue: 270000, achievedRevenue: 180000 }
    ]
  },
  {
    id: 'team-08',
    name: 'Team 08 - Vanguard Pioneers',
    division: 'IT Services & Digital Transformation',
    branchName: 'Bangalore Tech Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-08',
    teamLeadName: 'Divya Aggarwal',
    targetRevenue: 1500000,
    achievedRevenue: 1440000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-08-1'],
    bdmNames: ['Naveen Prasad'],
    bdeIds: ['m-08-2', 'm-08-3', 'm-08-4', 'm-08-5'],
    bdeNames: ['Pallavi Rao', 'Girish Reddy', 'Ankita Bhatt', 'Nitin Gadgil'],
    members: [
      { id: 'm-08-1', name: 'Naveen Prasad', role: 'BDM', targetRevenue: 350000, achievedRevenue: 360000 },
      { id: 'm-08-2', name: 'Pallavi Rao', role: 'BDE', targetRevenue: 300000, achievedRevenue: 310000 },
      { id: 'm-08-3', name: 'Girish Reddy', role: 'BDE', targetRevenue: 290000, achievedRevenue: 280000 },
      { id: 'm-08-4', name: 'Ankita Bhatt', role: 'BDE', targetRevenue: 280000, achievedRevenue: 260000 },
      { id: 'm-08-5', name: 'Nitin Gadgil', role: 'BDE', targetRevenue: 280000, achievedRevenue: 230000 }
    ]
  },
  {
    id: 'team-09',
    name: 'Team 09 - Quantum Force',
    division: 'Government Grants & Subsidies',
    branchName: 'Hyderabad Hub',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-09',
    teamLeadName: 'Saurabh Jain',
    targetRevenue: 1500000,
    achievedRevenue: 990000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-09-1', 'm-09-2'],
    bdmNames: ['Rajiv Nambiar', 'Swati Deshpande'],
    bdeIds: ['m-09-3', 'm-09-4', 'm-09-5'],
    bdeNames: ['Chetan Bhagat', 'Meenal Jain', 'Parth Shukla'],
    members: [
      { id: 'm-09-1', name: 'Rajiv Nambiar', role: 'BDM', targetRevenue: 350000, achievedRevenue: 250000 },
      { id: 'm-09-2', name: 'Swati Deshpande', role: 'BDM', targetRevenue: 300000, achievedRevenue: 210000 },
      { id: 'm-09-3', name: 'Chetan Bhagat', role: 'BDE', targetRevenue: 290000, achievedRevenue: 190000 },
      { id: 'm-09-4', name: 'Meenal Jain', role: 'BDE', targetRevenue: 280000, achievedRevenue: 180000 },
      { id: 'm-09-5', name: 'Parth Shukla', role: 'BDE', targetRevenue: 280000, achievedRevenue: 160000 }
    ]
  },
  {
    id: 'team-10',
    name: 'Team 10 - Velocity Kings',
    division: 'Business Loans & Working Capital',
    branchName: 'Hyderabad Hub',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-10',
    teamLeadName: 'Manish Pandey',
    targetRevenue: 1500000,
    achievedRevenue: 790000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-10-1'],
    bdmNames: ['Omkar Sathe'],
    bdeIds: ['m-10-2', 'm-10-3', 'm-10-4', 'm-10-5'],
    bdeNames: ['Simran Kaur', 'Akshay Gupte', 'Isha Singhal', 'Jayant Das'],
    members: [
      { id: 'm-10-1', name: 'Omkar Sathe', role: 'BDM', targetRevenue: 350000, achievedRevenue: 200000 },
      { id: 'm-10-2', name: 'Simran Kaur', role: 'BDE', targetRevenue: 300000, achievedRevenue: 170000 },
      { id: 'm-10-3', name: 'Akshay Gupte', role: 'BDE', targetRevenue: 290000, achievedRevenue: 155000 },
      { id: 'm-10-4', name: 'Isha Singhal', role: 'BDE', targetRevenue: 280000, achievedRevenue: 140000 },
      { id: 'm-10-5', name: 'Jayant Das', role: 'BDE', targetRevenue: 280000, achievedRevenue: 125000 }
    ]
  },
  {
    id: 'team-11',
    name: 'Team 11 - Falcon Dominators',
    division: 'Government Grants & Schemes',
    branchName: 'Ahmedabad Central',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-11',
    teamLeadName: 'Kavita Saxena',
    targetRevenue: 1500000,
    achievedRevenue: 875000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-11-1'],
    bdmNames: ['Bhavesh Patel'],
    bdeIds: ['m-11-2', 'm-11-3', 'm-11-4', 'm-11-5'],
    bdeNames: ['Dharmesh Shah', 'Hinal Trivedi', 'Ketan Gandhi', 'Jignesh Vora'],
    members: [
      { id: 'm-11-1', name: 'Bhavesh Patel', role: 'BDM', targetRevenue: 350000, achievedRevenue: 225000 },
      { id: 'm-11-2', name: 'Dharmesh Shah', role: 'BDE', targetRevenue: 300000, achievedRevenue: 190000 },
      { id: 'm-11-3', name: 'Hinal Trivedi', role: 'BDE', targetRevenue: 290000, achievedRevenue: 170000 },
      { id: 'm-11-4', name: 'Ketan Gandhi', role: 'BDE', targetRevenue: 280000, achievedRevenue: 150000 },
      { id: 'm-11-5', name: 'Jignesh Vora', role: 'BDE', targetRevenue: 280000, achievedRevenue: 140000 }
    ]
  },
  {
    id: 'team-12',
    name: 'Team 12 - Thunderbolts',
    division: 'Business Loans & Credit',
    branchName: 'Ahmedabad Central',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-12',
    teamLeadName: 'Deepak Rawat',
    targetRevenue: 1500000,
    achievedRevenue: 710000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-12-1', 'm-12-2'],
    bdmNames: ['Kashyap Mehta', 'Vaishali Modi'],
    bdeIds: ['m-12-3', 'm-12-4', 'm-12-5'],
    bdeNames: ['Chirag Darji', 'Monika Suthar', 'Alok Pandey'],
    members: [
      { id: 'm-12-1', name: 'Kashyap Mehta', role: 'BDM', targetRevenue: 350000, achievedRevenue: 180000 },
      { id: 'm-12-2', name: 'Vaishali Modi', role: 'BDM', targetRevenue: 300000, achievedRevenue: 150000 },
      { id: 'm-12-3', name: 'Chirag Darji', role: 'BDE', targetRevenue: 290000, achievedRevenue: 140000 },
      { id: 'm-12-4', name: 'Monika Suthar', role: 'BDE', targetRevenue: 280000, achievedRevenue: 125000 },
      { id: 'm-12-5', name: 'Alok Pandey', role: 'BDE', targetRevenue: 280000, achievedRevenue: 115000 }
    ]
  },
  {
    id: 'team-13',
    name: 'Team 13 - Horizon Knights',
    division: 'Government Schemes & Subsidies',
    branchName: 'Jaipur North Hub',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-13',
    teamLeadName: 'Shilpa Shetty',
    targetRevenue: 1500000,
    achievedRevenue: 560000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-13-1'],
    bdmNames: ['Raghavendra Rathore'],
    bdeIds: ['m-13-2', 'm-13-3', 'm-13-4', 'm-13-5'],
    bdeNames: ['Sonal Sharma', 'Lalit Meena', 'Anil Shekhawat', 'Priyanka Gehlot'],
    members: [
      { id: 'm-13-1', name: 'Raghavendra Rathore', role: 'BDM', targetRevenue: 350000, achievedRevenue: 145000 },
      { id: 'm-13-2', name: 'Sonal Sharma', role: 'BDE', targetRevenue: 300000, achievedRevenue: 120000 },
      { id: 'm-13-3', name: 'Lalit Meena', role: 'BDE', targetRevenue: 290000, achievedRevenue: 110000 },
      { id: 'm-13-4', name: 'Anil Shekhawat', role: 'BDE', targetRevenue: 280000, achievedRevenue: 95000 },
      { id: 'm-13-5', name: 'Priyanka Gehlot', role: 'BDE', targetRevenue: 280000, achievedRevenue: 90000 }
    ]
  },
  {
    id: 'team-14',
    name: 'Team 14 - Elite Centurions',
    division: 'Business Loans & MSME Credit',
    branchName: 'Kolkata East Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-14',
    teamLeadName: 'Rakesh Mishra',
    targetRevenue: 1500000,
    achievedRevenue: 480000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-14-1', 'm-14-2'],
    bdmNames: ['Subhashis Roy', 'Deblina Mukherjee'],
    bdeIds: ['m-14-3', 'm-14-4', 'm-14-5'],
    bdeNames: ['Tanmay Das', 'Poulomi Sen', 'Joydeb Ghosh'],
    members: [
      { id: 'm-14-1', name: 'Subhashis Roy', role: 'BDM', targetRevenue: 350000, achievedRevenue: 125000 },
      { id: 'm-14-2', name: 'Deblina Mukherjee', role: 'BDM', targetRevenue: 300000, achievedRevenue: 105000 },
      { id: 'm-14-3', name: 'Tanmay Das', role: 'BDE', targetRevenue: 290000, achievedRevenue: 95000 },
      { id: 'm-14-4', name: 'Poulomi Sen', role: 'BDE', targetRevenue: 280000, achievedRevenue: 80000 },
      { id: 'm-14-5', name: 'Joydeb Ghosh', role: 'BDE', targetRevenue: 280000, achievedRevenue: 75000 }
    ]
  },
  {
    id: 'team-15',
    name: 'Team 15 - Cyber Crusaders',
    division: 'IT Services & Software Solutions',
    branchName: 'Chennai South Branch',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-15',
    teamLeadName: 'Megha Roy',
    targetRevenue: 1500000,
    achievedRevenue: 640000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-15-1'],
    bdmNames: ['Karthik Ramanathan'],
    bdeIds: ['m-15-2', 'm-15-3', 'm-15-4', 'm-15-5'],
    bdeNames: ['Divya Swaminathan', 'Vijay Chandran', 'Deepa Krishnan', 'Arun Balaji'],
    members: [
      { id: 'm-15-1', name: 'Karthik Ramanathan', role: 'BDM', targetRevenue: 350000, achievedRevenue: 165000 },
      { id: 'm-15-2', name: 'Divya Swaminathan', role: 'BDE', targetRevenue: 300000, achievedRevenue: 135000 },
      { id: 'm-15-3', name: 'Vijay Chandran', role: 'BDE', targetRevenue: 290000, achievedRevenue: 125000 },
      { id: 'm-15-4', name: 'Deepa Krishnan', role: 'BDE', targetRevenue: 280000, achievedRevenue: 110000 },
      { id: 'm-15-5', name: 'Arun Balaji', role: 'BDE', targetRevenue: 280000, achievedRevenue: 105000 }
    ]
  },
  {
    id: 'team-16',
    name: 'Team 16 - Prime Achievers',
    division: 'Corporate Grants & Capital Schemes',
    branchName: 'Corporate HQ',
    branchManagerId: 'e-bm',
    branchManagerName: 'Pooja Deshmukh',
    teamLeadId: 'tl-16',
    teamLeadName: 'Varun Grover',
    targetRevenue: 1500000,
    achievedRevenue: 390000,
    activeLeadsCount: 0,
    createdAt: '2026-01-15',
    bdmIds: ['m-16-1', 'm-16-5'],
    bdmNames: ['Abhishek Vyas', 'Tarun Saxena'],
    bdeIds: ['m-16-2', 'm-16-3', 'm-16-4'],
    bdeNames: ['Nisha Sharma', 'Siddharth Roy', 'Monika Paul'],
    members: [
      { id: 'm-16-1', name: 'Abhishek Vyas', role: 'BDM', targetRevenue: 350000, achievedRevenue: 100000 },
      { id: 'm-16-2', name: 'Nisha Sharma', role: 'BDE', targetRevenue: 300000, achievedRevenue: 85000 },
      { id: 'm-16-3', name: 'Siddharth Roy', role: 'BDE', targetRevenue: 300000, achievedRevenue: 80000 },
      { id: 'm-16-4', name: 'Monika Paul', role: 'BDE', targetRevenue: 280000, achievedRevenue: 65000 },
      { id: 'm-16-5', name: 'Tarun Saxena', role: 'BDM', targetRevenue: 270000, achievedRevenue: 60000 }
    ]
  }
];
export const INITIAL_WFH_REQUESTS: WFHRequest[] = [];
export const INITIAL_PINNED_DEVICES: PinnedDevice[] = [];
